# Generated by Django 5.0.6 on 2024-05-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='product_image',
        ),
    ]
